DATA SCIENCE SPECIALISM

MODULE 4 - Exploratory Data Analysis

PROJECT 1
==================================================================================

PLOT 4 DETAILS -

Graph style	:	four graphs - 

				top left - global active power (as plot 2)
				
				bottom left - energy sub metering (as plot 3 without line around legend)
				
				top right - voltage against datetime
				
				bottom right - global reactive power against datetime

Graph size	:	480 pixels by 480 pixels

Graph title :	none

Dataset		:	dates 2007-02-01 and 2007-02-02 (1st & 2nd of February 2007)

=================================================================================

R SCRIPT

##1 - saving the output graph (as a png) generated by the R script below - automatically saved as size 480 x 480 pixels
png("plot4.png")
